apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: rabbitmq
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: rabbitmq
    chartVersion: 6.25.4

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values: {}

  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder: {}
