apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: kots-validation
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - data:
        collectorName: literals/a-literal-value
        data: |
          this is an example of a literal value included in a support bundle
          redact-me-first
    - data:
        collectorName: literals/a-config-value
        data: |
          this is an example of a value passed in from the config page and included in a support bundle
          repl{{ ConfigOption "company_name" }}
  analyzers:
    - deploymentStatus:
        name: nginx
        outcomes:
          - fail:
              when: "< 1"
              message: There are no ready replicas of Nginx.
          - warn:
              when: "= 1"
              message: There is exactly 1 ready replica of Nginx.
          - pass:
              message: There are multiple ready replicas of Nginx.
