apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: kots-validation
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - data:
        collectorName: literals/a-literal-value
        data: |
          this is an example of a literal value included in a support bundle
          redact-me-first
          redact-me-second
          mask-the-center
          remove-the-center
    - data:
        collectorName: literals/a-yaml-file
        data: |
          # this is a yaml file that can be redacted
          abc:
            xyz:
            - a: b
              c: d
            - a: e
              f: g

  analyzers:
    - deploymentStatus:
        name: nginx
        outcomes:
          - fail:
              when: "< 1"
              message: There are no ready replicas of Nginx.
          - warn:
              when: "= 1"
              message: There is exactly 1 ready replica of Nginx.
          - pass:
              message: There are multiple ready replicas of Nginx.
