apiVersion: databases.schemahero.io/v1alpha3
kind: Database
metadata:
  name: kotsvalidation
spec:
  immediateDeploy: true
  connection:
    mysql:
      uri:
        value: kotsvalidation:password@tcp(mysql.default.svc.cluster.local:3306)/kotsvalidation?parseTime=true
