apiVersion: databases.schemahero.io/v1alpha3
kind: Database
metadata:
  name: kotsvalidation-postgres
spec:
  immediateDeploy: true
  connection:
    postgres:
      uri:
        value: postgres://kotsvalidation:password@postgres.default.svc.cluster.local:5432/kotsvalidation?sslmode=disable
