apiVersion: databases.schemahero.io/v1alpha3
kind: Database
metadata:
  name: kotsbots-postgres
spec:
  immediateDeploy: true
  connection:
    postgres:
      uri:
        value: postgres://kotsbots:password@postgres.default.svc.cluster.local:5432/kotsbots?sslmode=disable
