---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: kotsvalidation-mysql
  labels:
    app: mysql
type: Opaque
stringData:
  uri: "mysql://kotsvalidation:password@mysql/kotsvalidation?connect_timeout=10&application_name=kotsvalidation&sslmode=disable"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: "remove-lost-found"
          image: "busybox:1.25.0"
          imagePullPolicy: IfNotPresent
          command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: kotsvalidation-datadir
              mountPath: /var/lib/mysql

      containers:
      - name: mysql
        image: kotsvalidation-mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: kotsvalidation
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: kotsvalidation
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        volumeMounts:
        - name: kotsvalidation-datadir
          mountPath: /var/lib/mysql

      volumes:
      - name: kotsvalidation-datadir
        persistentVolumeClaim:
          claimName: kotsvalidation-datadir

  volumeClaimTemplates:
  - metadata:
      name: kotsvalidation-datadir
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
