apiVersion: skaffold/v2beta2
kind: Config

build:
  local:
    useBuildkit: true
    concurrency: 0

  artifacts:
    - image: kotsvalidation-api
      context: "./api"
      docker:
        dockerfile: ./Dockerfile.skaffold

    - image: kotsvalidation-postgres
      context: "./migrations/fixtures"
      docker:
        dockerfile: ./deploy/Dockerfile

deploy:
  kustomize:
    paths: ["./kustomize/overlays/dev"]
    flags:
      apply:
        - --validate=false
