apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsvalidation-api
spec:
  selector:
    matchLabels:
      app: kotsvalidation-api
  template:
    metadata:
      labels:
        app: kotsvalidation-api
    spec:
      restartPolicy: Always
      containers:
        - name: kotsvalidation-api
          image: kotsvalidation-api
          imagePullPolicy: IfNotPresent
          command: ["/kotsvalidation-api", "run"]
          ports:
            - name: http
              containerPort: 3000
