apiVersion: v1
kind: Service
metadata:
  name: kotsvalidation-api
  labels:
    app: kotsvalidation-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
  selector:
    app: kotsvalidation-api
