apiVersion: v1
kind: Service
metadata:
  name: kotsvalidation-api
  labels:
    app: kotsvalidation-api
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    nodePort: 30000
  selector:
    app: kotsvalidation-api
