apiVersion: v1
kind: Secret
metadata:
  name: kotsbots-postgres
  annotations:
    "kots.io/when": '{{repl ConfigOptionEquals "postgres_type" "embedded_postgres"}}'
type: Opaque
stringData:
  uri: 'postgres://kotsbots:{{repl ConfigOption "embedded_postgres_password"}}@postgresql:5432/kotsbots?sslmode=disable'
