apiVersion: v1
kind: Secret
metadata:
  name: kotsvalidation-mysql
  annotations:
    "kots.io/when": '{{repl ConfigOptionEquals "mysql_type" "embedded_mysql"}}'
type: Opaque
stringData:
  uri: 'kotsvalidation:{{repl ConfigOption "embedded_mysql_password"}}@tcp(mysql:3306)/kotsvalidation?parseTime=true'
