apiVersion: v1
kind: Secret
metadata:
  name: kotsvalidation-postgres
  annotations:
    "kots.io/when": '{{repl ConfigOptionEquals "postgres_type" "embedded_postgres"}}'
type: Opaque
stringData:
  uri: 'postgres://kotsvalidation:{{repl ConfigOption "embedded_postgres_password"}}@postgresql:5432/kotsvalidation?sslmode=disable'
