apiVersion: v1
kind: Service
metadata:
  name: kotsvalidation-api
  labels:
    app: kotsvalidation-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
  selector:
    app: kotsvalidation-api
---
apiVersion: v1
kind: Service
metadata:
  name: kotsvalidation
  labels:
    app: kotsvalidation
  annotations:
    "kots.io/when": '{{repl ConfigOptionEquals "service_type" "node_port"}}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
  selector:
    app: kotsvalidation-api
---
apiVersion: v1
kind: Service
metadata:
  name: kotsvalidation-nodeport
  labels:
    app: kotsvalidation
  annotations:
    "kots.io/when": '{{repl ConfigOptionEquals "service_type" "node_port"}}'
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: http
    nodePort: repl{{ ConfigOption "node_port_port"}}
  selector:
    app: kotsvalidation-web
