apiVersion: v1
kind: Service
metadata:
  name: kotsbots-api
  labels:
    app: kotsbots-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
  selector:
    app: kotsbots-api
---
apiVersion: v1
kind: Service
metadata:
  name: kotsbots
  labels:
    app: kotsbots
  annotations:
    "kots.io/when": '{{repl ConfigOptionEquals "service_type" "node_port"}}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
  selector:
    app: kotsbots-api
---
apiVersion: v1
kind: Service
metadata:
  name: kotsbots-nodeport
  labels:
    app: kotsbots
  annotations:
    "kots.io/when": '{{repl ConfigOptionEquals "service_type" "node_port"}}'
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: http
    nodePort: repl{{ ConfigOption "node_port_port"}}
  selector:
    app: kotsbots-web
