apiVersion: batch/v1
kind: Job
metadata:
  name: kotsvalidation-migrations
  annotations:
    "kots.io/hook-delete-policy": "hook-succeeded, hook-failed"
spec:
  template:
    spec:
      volumes:
        - name: migrations
          emptyDir:
            medium: Memory
      restartPolicy: OnFailure
      initContainers:
        - image: kotsvalidation-migrations
          name: migrations-plan
          volumeMounts:
            - name: migrations
              mountPath: /migrations
          args: ["plan"]
          env:
            - name: SCHEMAHERO_DRIVER
              value: mysql
            - name: SCHEMAHERO_SPEC_FILE
              value: /tables
            - name: SCHEMAHERO_OVERWRITE
              value: "true"
            - name: SCHEMAHERO_OUT
              value: /migrations/plan.yaml
            - name: SCHEMAHERO_URI
              valueFrom:
                secretKeyRef:
                  name: kotsvalidation-mysql
                  key: uri
      containers:
        - image: kotsvalidation-migrations
          name: migrations-apply
          volumeMounts:
            - name: migrations
              mountPath: /migrations
          args: ["apply"]
          env:
            - name: SCHEMAHERO_DRIVER
              value: mysql
            - name: SCHEMAHERO_DDL
              value: /migrations/plan.yaml
            - name: SCHEMAHERO_URI
              valueFrom:
                secretKeyRef:
                  name: kotsvalidation-mysql
                  key: uri

